<?php
session_start();
require_once '../includes/db.php';
if(!isset($_SESSION['admin_id'])) die("Unauthorized");

$id = (int)($_GET['id'] ?? 0);
$stmt = $pdo->prepare("
    SELECT sq.*, 
           CASE WHEN sq.user_type = 'shop' THEN s.shop_name ELSE c.name END as sender_name,
           CASE WHEN sq.user_type = 'shop' THEN s.email ELSE c.email END as sender_email
    FROM support_queries sq
    LEFT JOIN shop_owners s ON sq.user_id = s.id AND sq.user_type = 'shop'
    LEFT JOIN customers c ON sq.user_id = c.id AND sq.user_type = 'customer'
    WHERE sq.id = ?
");
$stmt->execute([$id]);
$q = $stmt->fetch();
if(!$q) die("Ticket not found.");
?>
<!DOCTYPE html>
<html>
<head>
    <title>Ticket-<?= $id ?></title>
    <style>
        body { font-family: 'Inter', sans-serif; color: #1e293b; padding: 40px; line-height: 1.5; }
        .header { border-bottom: 2px solid #0f172a; padding-bottom: 20px; margin-bottom: 30px; }
        .ticket-info { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 20px; border-radius: 12px; margin-bottom: 20px; }
        .label { font-size: 10px; font-weight: 800; color: #64748b; text-transform: uppercase; margin-bottom: 5px; }
        .value { font-size: 14px; font-weight: 700; }
        .status { padding: 4px 12px; border-radius: 99px; font-size: 10px; font-weight: 800; text-transform: uppercase; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>
    <div class="no-print" style="text-align:right; margin-bottom: 20px;">
        <button onclick="window.print()">Print / Save PDF</button>
    </div>
    <div class="header">
        <img src="https://i.ibb.co/VcCqLXtW/Chat-GPT-Image-Apr-27-2026-03-04-41-PM.png" height="40">
        <h2>Official Support Transcript</h2>
    </div>
    <div class="ticket-info">
        <div>
            <div class="label">Ticket Reference</div>
            <div class="value">#TK-<?= $id ?></div>
        </div>
        <div>
            <div class="label">Current Status</div>
            <div class="value uppercase"><?= $q['status'] ?></div>
        </div>
        <div style="text-align:right">
            <div class="label">Date Created</div>
            <div class="value"><?= date('d M Y, h:i A', strtotime($q['created_at'])) ?></div>
        </div>
    </div>
    <div class="box">
        <div class="label">From (<?= ucfirst($q['user_type']) ?>)</div>
        <div class="value"><?= htmlspecialchars($q['sender_name']) ?> (<?= htmlspecialchars($q['sender_email']) ?>)</div>
    </div>
    <div class="box">
        <div class="label">Subject</div>
        <div class="value"><?= htmlspecialchars($q['subject']) ?></div>
    </div>
    <div class="box" style="background:#fff">
        <div class="label">Message Description</div>
        <div class="value" style="font-weight:400"><?= nl2br(htmlspecialchars($q['message'])) ?></div>
    </div>
    <div class="box" style="border-left: 5px solid #2563eb;">
        <div class="label" style="color:#2563eb">Admin Official Response</div>
        <div class="value" style="font-weight:500"><?= $q['reply'] ? nl2br(htmlspecialchars($q['reply'])) : '<i>Pending response from admin.</i>' ?></div>
    </div>
    <div style="margin-top:50px; text-align:center; font-size:10px; color:#94a3b8;">
        This is an automated transcript generated by KhataLink Support System.
    </div>
</body>
</html>